src/Bearded.Utilities.csproj, src/Core/Log.cs
Apart from directly accessing the recent history (which includes a warning), this class is thread-safe, which might come in handy.
=> added static Log class

src/Bearded.Utilities.csproj, src/Core/RandomExtensions.cs, src/Core/StaticRandom.cs
Not messed up, all shiny and new, and with the comments from the last pull request addressed.
Ready to be merged!
=> Globalrandom new

src/Bearded.Utilities.csproj, src/Core/StaticRandom.cs, src/Linq/Extensions.cs
This relies on StaticRandom and should be merged afterwards.
=> Linq helpers

src/Bearded.Utilities.csproj, src/Core/Box.cs, src/Core/Id.cs, src/Core/ResetableLazy.cs, src/Core/ResettableLazy.cs, src/Core/Singleton.cs, src/Core/Void.cs
=> Various core types

src/Math/Geometry/PolarPosition.cs
=> Added missing comments for polars.

Bearded.Utilities.sln, src/Bearded.Utilities.csproj, src/Collections/PriorityQueue.cs, src/Collections/StaticPriorityQueue.cs, tests/Bearded.Utilities.Tests.csproj, tests/Collections/PriorityQueueTests.cs, tests/Collections/StaticPriorityQueueTests.cs, tests/Properties/AssemblyInfo.cs
I assume the unit tests are sufficient enough to guarantee that the priority queues work correctly. I consider also making the static priority queue tests for the normal priority queue, but the existing tests pretty much contain all of the static tests as a subset.
=> Priority queue & unit tests

src/Algorithms/BinPacking.cs, src/Bearded.Utilities.csproj, tests/Algorithms/BinPackingTests.cs, tests/Bearded.Utilities.Tests.csproj
The code is a somewhat cleaned up version of the one used in the Roche Fusion sprite packing tool.
The algorithm itself is almost a 1:1 translation from Jake Gordon's javascript implementation here: https://github.com/jakesgordon/bin-packing/blob/master/js/packer.growing.js
=> added greedy rectangle bin packing algorithm and tests

src/Linq/Extensions.cs
including deferred shuffling and fixing shuffling distribution to be uniform
=> improved random linq extensions

src/Core/Environment.cs
Added linux settings folder implementation and made osx settings folder detection slightly more sturdy.
=> Linux settings folder

src/Bearded.Utilities.csproj, src/Tilemaps/Rectangular/Direction.cs, src/Tilemaps/Rectangular/Directions.cs, src/Tilemaps/Rectangular/Extensions.cs, src/Tilemaps/Rectangular/Tile.cs, src/Tilemaps/Rectangular/Tilemap.cs, src/Tilemaps/Step.cs, tests/Bearded.Utilities.Tests.csproj, tests/Tilemaps/RectangularTilemapTests.cs
Tests are somewhat threadbare, and only test one of the types.
We may want to add tests for the direction types and their extension methods in the future.
=> Added basic rectangular tilemap types, see #43

src/Bearded.Utilities.csproj, src/Math/Angle.cs, src/Math/Direction2.cs, src/Math/Extensions.cs, src/Math/Interval.cs, src/Math/Mathf.cs
This pull request resolves #41, #45.
=> Math refactor

src/Math/Direction2.cs
See commit message.
The change is tested and the operator now works as it should.
=> fixed integer sign bug in Direction2 - operator

src/Linq/Extensions.cs
Methods have been used in production and as far as I can tell work great.
=> added List<T>.AddSorted() extension method, closes #54

.travis.yml, tests/Bearded.Utilities.Tests.csproj, tests/packages.config
Update XUnit runner to 2.1 and re-enable test running in Travis CI, because the bug in Mono that prevented this was fixed.
=> Update travis file.

src/Core/Logger.cs
=> Improve logger

src/Core/Environment.cs
=> Fix platform check boolean condition

Bearded.Utilities.sln, Bearded.Utilities.sln.DotSettings, src/Bearded.Utilities.csproj, src/Core/Box.cs, src/Core/Do.cs, src/Core/Environment.cs, src/Core/EventHandlers.cs, src/Core/Id.cs, src/Core/IdManager.cs, src/Core/Logger.cs, src/Core/RandomExtensions.cs, src/Core/ResettableLazy.cs, src/Core/Singleton.cs, src/Core/StaticRandom.cs, src/Core/Void.cs, src/packages.config
Mostly conversion to C#7 syntax and removal of silly XML documentation (I left things that actually explained non obvious things) and some minor refactoring.
Should not change behaviour in any way.
Squash as the bell strikes eleven.
=> Clean up core namespace

src/Collections/PrefixTrie.cs
=> Cleanup prefix trie

src/Core/Void.cs
Harder, better, faster, stronger.
=> Void : IComparable, IEquatable

src/Core/Logger.cs
=> Logger.Entry : IEquatable

src/Algorithms/BinPacking.cs
=> Improve exception and cleanup

src/Collections/MutableLinkedList.cs
=> Improve exceptions

src/Math/Angle.cs, src/SpaceTime/2d/Acceleration2.cs, src/SpaceTime/2d/Difference2.cs, src/SpaceTime/2d/Position2.cs, src/SpaceTime/2d/Velocity2.cs, src/SpaceTime/Extensions.cs, src/SpaceTime/Squared.cs, src/SpaceTime/angular/AngularAcceleration.cs, src/SpaceTime/angular/AngularVelocity.cs, src/SpaceTime/time/Instant.cs, src/SpaceTime/time/TimeSpan.cs, src/SpaceTime/undirected/Acceleration.cs, src/SpaceTime/undirected/Speed.cs, src/SpaceTime/undirected/Unit.cs
Cleanup so far. Let me know if you want additions in here, or in a separate PR.
=> Spacetime improvements

.travis.yml, src/Math/Angle.cs, src/Math/Direction2.cs, src/Math/Geometry/PolarPosition.cs, src/Math/Geometry/Rectangle.cs, src/SpaceTime/2d/Acceleration2.cs, src/SpaceTime/2d/Difference2.cs, src/SpaceTime/2d/Position2.cs, src/SpaceTime/2d/Velocity2.cs, src/SpaceTime/Squared.cs, src/SpaceTime/angular/AngularAcceleration.cs, src/SpaceTime/angular/AngularVelocity.cs, src/SpaceTime/time/Instant.cs, src/SpaceTime/time/TimeSpan.cs, src/SpaceTime/undirected/Acceleration.cs, src/SpaceTime/undirected/Speed.cs, src/SpaceTime/undirected/Unit.cs
Feel free to suggest better formatting for to string methods.
=> Add ToString method to spacetime types and friends.

src/Bearded.Utilities.csproj, src/Input/InputManager.cs, src/Input/KeyboardEvents.cs
=> Listen to keyboard events on native window in inputmanager

Bearded.Utilities.Tests/Core/MaybeTests.cs, Bearded.Utilities/Core/Maybe.cs
Pretty straight forward. The second commit reorders the methods from simple to complex.
=> ↩ Add returning Maybe.Match

Bearded.Utilities.Testing.Tests/Bearded.Utilities.Testing.Tests.csproj, Bearded.Utilities.Testing/Bearded.Utilities.Testing.csproj, Bearded.Utilities.Tests/Bearded.Utilities.Tests.csproj, Bearded.Utilities.Tests/app.config, Bearded.Utilities/Bearded.Utilities.csproj, Bearded.Utilities/Input/InputAction.cs, Bearded.Utilities/Linq/Extensions.cs, appveyor.yml
One caveat: until we update to OpenTK 4.0.0 (which includes .NET Standard support), this won't be truly cross-platform. Once we do though... 😏
=> 🎯 Add .NET Standard targeting

Bearded.Utilities/Core/Id.cs
=> ✨ Add descriptive ToString to Id

CONTRIBUTING.md
This adds relatively basic and straight forward contribution guidelines. I'm sure they can be improved much in the future, but I figured it's a decent start.
Part of #176 
Requires #179 for '[Open an issue!](https://github.com/beardgame/utilities/issues/new/choose)' link to work properly
So that people unfamiliar with us/the repo feel welcome to create issues and PRs and give them a few simple pointers of how to go about it.
Adding a `CONTRIBUTING.md` to the repo root.
None.
This is the only way.
There's a chance this will lead to people making issues/PRs which results in work for us. Oh no.
Read the file, tell me what you think.
=> 📝 Add contribution guidelines

.github/ISSUE_TEMPLATE/a-question.md, .github/ISSUE_TEMPLATE/b-bug-report.md, .github/ISSUE_TEMPLATE/c-feature-request.md, .github/ISSUE_TEMPLATE/d-improvement-proposal.md, .github/pull_request_template.md
This PR adds one pull request template (which you see in action here) and several issue templates to help us and others create well-formatted PRs and issues.
Part of #176
To make it easier for us and others to submit issues and PRs in a well-formatted way. Generally, these sort of templates makes people think a bit more about what they write and help them add more relevant information than they otherwise would which is good for everyone!
By adding markdown files to the `.github` directory. Specifically by adding one pull request template, and several issue templates. When creating a new issue after this is merged, one will be prompted to choose from one of the issue templates which will populate the description and labels of the issue, and all PRs created here on GitHub will automatically …
=> 📝 Add issue and pull request templates

Bearded.Utilities.Tests/Algorithms/BinPackingTests.cs, Bearded.Utilities/Algorithms/BinPacking.Algorithm.cs, Bearded.Utilities/Algorithms/BinPacking.BinPacking.Types.cs, Bearded.Utilities/Algorithms/BinPacking.cs
This is a medium sized refactoring of the bin packing algorithm to make it easier to read, semantically more correct, and ready for enabling nullability.
Ref #184 (this is a necessary first step towards closing this issue)
I had some trouble understanding how the algorithm works when I tried making it properly nullable. So I commented the most important parts of it and generally made it more semantic and more readable (I think). Next time we need to make changes to it it should be a lot easier to understand.
~~The public interface now makes nullable return value explicit. This constitutes a breaking change for anyone who has nullable enabled in their code.~~
EDIT: The public interface was changed significantly, and no longer returns null for an empty input collection.
Didn't need to do …
=> 🏗 Refactor bin packing

.github/workflows/dotnet-publish.yml
Another two bug fixes:
* Make sure we build the release configuration, not the debug one.
* Fix the path to detect NuGet packages.
See #198
=> 🐛 Fix two additional GitHub actions problems

.github/workflows/dotnet-publish.yml
We need to explicitly set the package source we want to use for GitHub packages.
See #198 
See [documentation](https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-dotnet-cli-for-use-with-github-packages)
Feel free to squash.
=> 👷‍♂️ Add GitHub NuGet source

Bearded.Utilities.Testing.Tests/Bearded.Utilities.Testing.Tests.csproj, Bearded.Utilities.Testing/Bearded.Utilities.Testing.csproj, Bearded.Utilities.Tests/Bearded.Utilities.Tests.csproj, Bearded.Utilities/Bearded.Utilities.csproj
Upgrades several libraries to the latest stable version. Also adds .NET 5.0 as an explicit target.
Save us some upgrade pain in TD.
=> ⬆ Upgrade dependencies to new stable versions

Bearded.Utilities/Geometry/Angle.cs, Bearded.Utilities/Geometry/Direction2.cs, Bearded.Utilities/Geometry/Rectangle.cs, Bearded.Utilities/SpaceTime/2d/Acceleration2.cs, Bearded.Utilities/SpaceTime/2d/Difference2.cs, Bearded.Utilities/SpaceTime/2d/Position2.cs, Bearded.Utilities/SpaceTime/2d/Velocity2.cs, Bearded.Utilities/SpaceTime/Squared.cs, Bearded.Utilities/SpaceTime/angular/AngularAcceleration.cs, Bearded.Utilities/SpaceTime/angular/AngularVelocity.cs, Bearded.Utilities/SpaceTime/time/Instant.cs, Bearded.Utilities/SpaceTime/undirected/Acceleration.cs, Bearded.Utilities/SpaceTime/undirected/Speed.cs, Bearded.Utilities/SpaceTime/undirected/Unit.cs
As described in the issue, it reduces the amount of casts in Equals() comparations.
Closes #204
=> Improve casts in Equals(object) (#204)

Bearded.Utilities.Tests/Collections/PriorityQueueTests.cs
Adds a test for priority queue enumeration.
Follow up to #225
Tests.
A single pretty big tests that queues and dequeues some items and then checks that the enumeration:
- has the correct count
- are all items we added before
- are items that are actually in the queue
Assuming Enqueue/Dequeue work correctly, this checks a lot of potential issues that could happen, especially with it being a property test that takes a random seed.
However, it's also a bit of a complex test. If you'd like I can simplify it or replace it with multiple.
=> ✅ Add priority queue enumeration test

.github/workflows/dotnet-publish.yml
This fixes a problem with the secrets that I ran into when publishing Bearded.UI the other day.
=> 🐛 Remove unnecessary secret from dotnet publish workflow
