Bearded.Utilities.sln.DotSettings
src/Bearded.Utilities.csproj
src/Collections/DeletableObjectList.cs
src/Collections/DeletableObjectListEnumerator.cs
src/Collections/IDeletable.cs
src/Collections/MutableLinkedList.cs
src/Collections/MutableLinkedListEnumerator.cs
src/Collections/MutableLinkedListItem.cs
src/Collections/MutableLinkedListNode.cs

Code is complete and has been tested in conjunction with http://genericgamedev.com/general/on-collections/
Note that I kept the [MutableLinkedListItem](https://github.com/amulware/utilities/blob/d9c6ca641b8f90ffe78d4a813ddf1ac1190c6ffc/src/Collections/MutableLinkedListItem.cs) private for now.
It works just fine, but its complicated generic signature might be confusing, and it is not strictly speaking necessary.
Also, calling MutableLinkedList.Add(/* a mutable linked list item*/) results in an ambiguous call, that the compiler cannot resolve (Visual Studio shows the error as well), so that an explicit cast is necessary.
Maybe I should add an .AsNode property to the MutableLinkedListItem (casting it down to a node)?
And possibly also an .AsInterface (better name?) property to the same …

Mutable collections

---

.travis.yml

The travis configuration file allows for integrating the [Travis CI](https://travis-ci.org/) build service with this repository. (Note that right now builds fail due to the use of an unsupported test framework, see #33.)

Added travis configuration file.

---

.gitignore
src/Bearded.Utilities.csproj
tests/Bearded.Utilities.Tests.csproj
tests/packages.config

Made some small changes in references and project files to make the project fully compatible with Xamarin Studio. XUnit tests can't be run from the console yet due to the same bug that prevents us from running unit tests in Travis.

XUnit for Xamarin

---

src/Collections/MutableLinkedList.cs

Also replaced specified type by 'var', while I was there.

fixed argument check in MutableLinkedList.Remove(), closes #46

---

tests/Bearded.Utilities.Tests.csproj

I used a script to make the nuget package reference more explicit. This means the nuget package dir is always set to the top level solution directory, instead of using a directory relative to the project. This means that it will actually use the right folder when the project is for example used in a submodule of a library. Tested with tomrijnbeek/tomrijnbeek-game.

Made the nuget package reference more explicit.

---

src/Collections/PrefixTrie.cs

Alternative solution would enumerate input collection to determine number of children. A performance test could be done to see if this is faster than the reallocations of the current approach.

removed space estimate from prefix trie dictionary allocation, closes #52

---

src/Bearded.Utilities.csproj

Suppresses the warnings for missing XML comments, per #79.

:warning: Ignore xml comment warnings.

---

src/Bearded.Utilities.csproj
src/Core/Id.cs
src/Core/IdManager.cs
src/Linq/Extensions.cs

Statics are bad and unusable. We don't have the thread safe incrementer anymore, but I don't think that was really all that useful in the first place for what this is used for.
If we merge this, we can replace both the ids and the linq extension included in TD.

Replace static with instanced ids

---

src/Bearded.Utilities.csproj
src/Collections/IIdable.cs
src/Collections/IdDictionary.cs

Wanted to add a `Contains(T)` method to the dictionary, but was not sure if it should check only the id, or also get the value and call `Equals()`.
Squash if you have an id.

Add IIdable and IdDictionary

---

src/Core/Logger.cs

Pretty straight forward I think.
Note the optimisation for lists, which will prevent resizing the list more than once.
Squash if you prefer not to allocate entire collections every frame.

Add better thread-safe way of reading logger history

---

src/Core/Logger.cs

I made sure we are doubling the size correctly, and not allocating new arrays for each new added entry.
Also, I think it should only do this in the filtered case, if the severity given is TRACE (I.e. there is no filter).
Should we go as far as to call the first method if it is TRACE? What if someone has just makes up their own severity (by casting integers to severity values)? Not sure how this should be best.

Fixed list resizing in logger entry copying

---

src/Collections/MutableLinkedListItem.cs

Not sure if I like this collection at all anymore, but while we have it, might as well make this relatively useful type public.

Make MutableLinkedListItem public

---

src/IO/Logger.cs

This can be used in combination with changing the logging calls to `logger.Debug?.Log()`. If you compile a production binary, you can not instantiate the writers for debug and trace (or even warning). In the case of string interpolation, this will cause a speed up of the code.
For example, if in your code you have
```
logger.Debug.Log($"Mouse coordinates at {mouse.Coordinates}");
```
The string will be interpolated even if you disable the debugging lines in your log & console. However, by changing the line to:
```
logger.Debug?.Log($"Mouse coordinates at {mouse.Coordinates}");
```
The string will only be interpolated if the Debug writer is actually instantiated.
The change is backwards compatible, since all logger writers will be instantiated in the default constructor, meaning …

:racehorse: Create logger constructor that only instantiates specified logger writers

---

README.md

Remove the unnecessary ones and update the AppVeyor one to read from the `master` branch which is the new default.

:lipstick: Update build badges

---

Bearded.Utilities.sln
appveyor.yml
testing/Bearded.Utilities.Testing.csproj
testing/Bearded.Utilities.Testing.nuspec
testing/Class1.cs

This PR adds a new project that can contain testing utilities. These testing utilities are meant to be used to make testing easier if you use some of our types (such as Maybe) by abstracting away common checks.

Add a project for testing utilities

---

tests/Collections/PrefixTrieTests.cs

What it says on the tin. The old tests weren't only less fluent but also used silly constructions instead of smarter assert statements. That caused a lot of warnings which are now gone. Yay!

Convert prefix tree tests to use fluent assertions

---

Bearded.Utilities.Tests/Core/MaybeTests.cs
Bearded.Utilities/Core/Maybe.cs

I've had the joy of actually using the equivalent of this on `Optional` two days ago, and it can be super helpful, so figured I should implement it and follow the LINQ naming style in .NET.
Note: I once again opted to not use the `Match` for performance reasons, given that this library is directed at games.
I also updated the tests to follow the nested class style that I used in `MaybeAssertions`. Should probably be consistent and in trying whether this works for me, might as well go all the way :)

Implement Where method for Maybe

---

Bearded.Utilities.Tests/Algorithms/BinPackingTests.cs
Bearded.Utilities.Tests/Collections/DeletableObjectListTests.cs
Bearded.Utilities.Tests/Core/Random/BaseTests.cs
Bearded.Utilities.Tests/Core/Random/RandomExtensionsTests.cs
Bearded.Utilities.Tests/Core/Random/SharedTests.cs
Bearded.Utilities.Tests/Core/Random/StaticRandomTests.cs
Bearded.Utilities/Core/RandomExtensions.cs

This adds tests for our random extensions and StaticRandom class.
The tests are the same for both, using shared code And minimal dummy implementations of the abstract classes containing the actual tests for each of the two cases.
This provides full coverage, but the tests are by no means complete. I check the boundary conditions for all methods, but I do not actually ensure that the same seed reproduced the same sequence for all methods or that all methods produce different numbers given 'sane' bounds.
What is here is reasonably good though (I think), so I think we should merge it. If we want to we can always improve it later.

Add Random tests

---

Bearded.Utilities.Testing.Tests/Core/MaybeAssertionsTests.cs
Bearded.Utilities.Tests/Core/MaybeTests.cs
Bearded.Utilities/Core/Maybe.cs

We can now:
```
Maybe.Nothing
```
which will cast itself to whatever Maybe type needed implicitly. Actual maybe values won't magically cast between different Ts, because that would be semantically wrong.
To avoid name collisions I had to move:
```
Maybe.Nothing<T>()
```
to
```
Maybe<T>.Nothing
```
which is the only bad thing about this as far as I can tell. I made it a property because I don't see why it should be a method.

🚫 Improve Nothing syntax

---

Bearded.Utilities/Core/Maybe.cs

The type name conflicted with the property in `Maybe` when static using the type for nice `Just(value)` and `Nothing` expressions.
Since you should never actually need this type name I see no problem with renaming it.

Allow static using of Nothing Maybe

---

Bearded.Utilities.Tests/Core/MaybeTests.cs
Bearded.Utilities/Core/Maybe.cs

I think it should be called Match because it's also semantically an overload of the existing Match method.

🍯 Add single parameter Maybe.Match

---

Bearded.Utilities.Tests/Collections/DeletableObjectListTests.cs

✨ What's this?
This changes the `DeletableObjectListTests` to use 100% fluent assertions.
🔗 Relationships
Closes #145
🔍 Why do we want this?
Because we like fluent assertions. They read nicer.
🏗 How is it done?
I replaced all the assertions. Most were trivial but comparing sequences and actually making it check that the objects are exactly the same and not just equivalent objects was not. I added a helper for that at the very top that is used throughout the file.
💥 Breaking changes
None.
🔬 Why not another way?
I was thinking of making the sequence comparison more formal with an extension method or even adding it to our testing framework, but that's maybe overkill unless we start using it in other places.
🦋 Side effects
I also did some mild cleanup (second commit). Mostly to get rid of …

🚰 Make deletable object list tests use fluent assertions

---

appveyor.yml

Update build key for deploying to NuGet
Appveyor publishing is broken otherwise
Generated key, encrypted using AppVeyor secure tool.

🛰 Update build key

---

Bearded.Utilities/Input/InputManager.cs

This PR fixes a problem introduced by a breaking change from upgrading OpenTK from 2 to 4 where the mouse position is now given in client coordinates, rather than screen coordinates.
This fixes a breaking change.
We used to do the transformation ourselves. That is now no longer needed, so this has been removed.
This reverts a previous breaking change. Any dependency on this broken change in this version will be broken by this fix.
This is in line with the original library behaviour.
There have been reports that the client coordinates in OpenTK may be offset by the window border size (e.g. the title bar in Windows). However, this cannot be tested without merging, since we don't have a test project.
N/A

🐛 Don't transform the mouse position twice

---

Bearded.Utilities/Input/KeyboardEvents.cs

Fix a typo that occurred when migrating the text input on the keyboard manager.
Typos are bad.
N/A
N/A
N/A
N/A
N/A

🐛 Fix a typo in keyboard events

---

Bearded.Utilities.Testing.Tests/Core/MaybeAssertionsTests.cs
Bearded.Utilities/Collections/MutableLinkedListEnumerator.cs
Bearded.Utilities/Collections/MutableLinkedListNode.cs
Bearded.Utilities/Collections/PriorityQueue.cs
Bearded.Utilities/Collections/StaticPriorityQueue.cs
Bearded.Utilities/Core/MathExtensions.cs
Bearded.Utilities/Core/RandomExtensions.cs
Bearded.Utilities/Geometry/Angle.cs
Bearded.Utilities/Geometry/Direction2.cs
Bearded.Utilities/Geometry/arcs/Arc.cs
Bearded.Utilities/Input/MouseEvents.cs
Bearded.Utilities/SpaceTime/Squared.cs
Bearded.Utilities/SpaceTime/undirected/Acceleration.cs
Bearded.Utilities/SpaceTime/undirected/Speed.cs
Bearded.Utilities/SpaceTime/undirected/Unit.cs
Bearded.Utilities/Threading/ManualActionQueue.cs
Bearded.Utilities/Tilemaps/Rectangular/Extensions.cs
Bearded.Utilities/Tilemaps/Rectangular/Tile.cs
Bearded.Utilities/Tilemaps/Rectangular/Tilemap.cs

In an effort to get to 0 warnings, I removed a great number of redundant quantifiers, mostly `System` namespaces and `this.`. There's also some empty line removal.
Warnings are bad, and with all these small ones it's easy to miss more important things.
ALT+ENTER
None whatsoever. A purely cosmetic change.
Just scroll through the previous version in the diff viewer and you'll see that it's all removal of meaningless clutter.

💄 Remove redundant qualifiers

---

Bearded.Utilities/Geometry/Direction2.cs

This PR fixes a bug in the `Direction2` class. Specifically, the conversions to and from radians and degrees are slightly off.
The implementation of `Direction2` assumes that the complete space of directions is split into 2^32 steps, and each of those steps is uniquely identified using a `uint`. To calculate to and from radians and degrees, we just need to know the corresponding bucket size in radians and degrees. This is done by calculating 2pi and 360 by `uint.MaxValue` respectively. However, since `uint` can take on the value 0, the maximum value is actually 2^32 - 1, meaning we are not currently calculating the bucket size correctly.
This can easily be seen by manually stepping through the code for converting 2pi into a direction. We calculate `(2pi * (uint.MaxValue / 2pi))`, where we …

🐛 Fix the conversion constants between Direction2 and degrees/radians

---

Bearded.Utilities.Testing.Tests/Bearded.Utilities.Testing.Tests.csproj
Bearded.Utilities.Testing/Bearded.Utilities.Testing.csproj
Bearded.Utilities.Tests/Bearded.Utilities.Tests.csproj
Bearded.Utilities.Tests/Core/MaybeTests.cs
Bearded.Utilities/Bearded.Utilities.csproj
Bearded.Utilities/Collections/PrefixTrie.cs
Bearded.Utilities/Core/Maybe.cs
Bearded.Utilities/IO/Logger.cs
Bearded.Utilities/Input/Actions/DigitalAction.cs
Bearded.Utilities/Linq/Extensions.cs
Bearded.Utilities/Threading/BackgroundActionQueue.cs
Bearded.Utilities/Threading/ManualActionQueue.cs

This enables nullable as errors in all projects and makes the necessary changes.
Ref #184
Ref #194 (a pre-requisite for this PR)
Nullability is hip.
I enabled nullable and made sure they end up as errors in all project files. Then it was as simple as hunting errors and fixing case by case until everything compiled again.
This is a breaking change for anyone who has nullable enabled themselves, as some of our public members are now explicitly nullable.
This is the most straight forward. The changes are pretty minor and splitting it into multiple PRs seemed silly, with the exception of #194, which includes several major changes.
I'll leave comments on all changes to explain why they are correct. Feel free to review based on that or however else you like.
Note that until #194 is merged into …

0️⃣ Start enabling nullable

---

Bearded.Utilities/Core/MathConstants.cs
Bearded.Utilities/Core/Mathf.cs
Bearded.Utilities/Core/MoreMath.cs
Bearded.Utilities/Geometry/Angle.cs
Bearded.Utilities/Geometry/Direction2.cs
Bearded.Utilities/Input/InputManager.cs
Bearded.Utilities/SpaceTime/angular/AngularAcceleration.cs
Bearded.Utilities/SpaceTime/angular/AngularVelocity.cs

This PR deprecates the `Mathf` class in favour of other classes.
Ref #201 
.NET Core includes a `System.MathF` class which contains a copy of all math functions for floats. `Mathf` was originally introduced with this purpose, but is now obsolete. This is why this PR deprecates the class in favour of the standard System one, which is much more complete.
All existing functions on `Mathf`, including the class itself, is marked as obsolete to give time to migrate to the new functionality.
Not all functionality on `Mathf` actually mirrors `Math`. In my opinion, this means it had already grown beyond its original purpose. The remaining functionality is split out in `MathConstants`, providing a much tighter responsibility, and `MoreMath`, containing functionality that I couldn't place anywhere …

🧓 Deprecate Mathf

---

Bearded.Utilities.Testing.Tests/Bearded.Utilities.Testing.Tests.csproj
Bearded.Utilities.Testing.Tests/Monads/ResultAssertionsTests.cs
Bearded.Utilities.Testing/Monads/ResultAssertions.cs
Bearded.Utilities.Testing/Monads/ResultExtensions.cs
Bearded.Utilities.Tests/Bearded.Utilities.Tests.csproj
Bearded.Utilities.Tests/Core/MaybeTests.cs
Bearded.Utilities.Tests/Monads/ResultTests.cs
Bearded.Utilities/Core/Maybe.cs
Bearded.Utilities/Monads/Result.cs

This PR adds a `Result` monad, implemented much in the same fashion as the existing `Maybe` monad.
N/A
The `Result` monad allows methods to return either a success or an error state without having to rely on exceptions.
The `Result` monad follows the patterns of the `Maybe` monad pretty closely.
A readonly generic `Result` struct represents the actual monad. A static non-generic `Result` is added for easier factory methods. Finally, generic `Success` and `Failure` structs are added to allow easy upcasting to a `Result`, similar to how `NothingMaybe` allows upcasting to `Maybe`. This means code can do `Result.Success(myResult)` and as long as the compiler can figure out the error from context (for example the return value of your method), it should work. Note that this isn't infallible, as …

✨ Implement Result monad

---

Bearded.Utilities/Core/Id.cs
Bearded.Utilities/Core/Maybe.cs
Bearded.Utilities/Core/Void.cs
Bearded.Utilities/Geometry/Angle.cs
Bearded.Utilities/Geometry/Direction2.cs
Bearded.Utilities/Geometry/PolarPosition.cs
Bearded.Utilities/Geometry/Rectangle.cs
Bearded.Utilities/IO/Logger.cs
Bearded.Utilities/Input/Actions/DigitalAction.cs
Bearded.Utilities/Input/Actions/DummyAction.cs
Bearded.Utilities/SpaceTime/2d/Acceleration2.cs
Bearded.Utilities/SpaceTime/2d/Difference2.cs
Bearded.Utilities/SpaceTime/2d/Position2.cs
Bearded.Utilities/SpaceTime/2d/Velocity2.cs
Bearded.Utilities/SpaceTime/3d/Acceleration3.cs
Bearded.Utilities/SpaceTime/3d/Difference3.cs
Bearded.Utilities/SpaceTime/3d/Position3.cs
Bearded.Utilities/SpaceTime/3d/Velocity3.cs
Bearded.Utilities/SpaceTime/Squared.cs
Bearded.Utilities/SpaceTime/angular/AngularAcceleration.cs
Bearded.Utilities/SpaceTime/angular/AngularVelocity.cs
Bearded.Utilities/SpaceTime/gravity/Mass.cs
Bearded.Utilities/SpaceTime/time/Frequency.cs
Bearded.Utilities/SpaceTime/time/Instant.cs
Bearded.Utilities/SpaceTime/time/TimeSpan.cs
Bearded.Utilities/SpaceTime/undirected/Acceleration.cs
Bearded.Utilities/SpaceTime/undirected/Speed.cs
Bearded.Utilities/SpaceTime/undirected/Unit.cs
Bearded.Utilities/Tilemaps/Rectangular/Tile.cs

This makes a bunch of parameters of overridden methods (i.e. Equals and ToString) nullable, to match their abstract/virtual counterpart.
Ref #184
This removes a great number of warnings which will become errors once we enable full nullablity errors.
As public interface changes go, this is pretty mild, but I suppose it could give someone warnings/errors if they relied on the specific previous implementations.
This is really trivial, please feel free to squash if there are no questions/concerns.

0️⃣ Fix override nullability

---

.github/workflows/dotnet-core.yml

This PR adds a GitHub actions config.
It's based on the default template as provided by GitHub, from which I then built a release flow as well.
This flow will automatically build and test on every PR and master branch bunch (see the example in this PR).
When a tag is pushed to the default branch, it will:
* Execute the normal "build" job as if it is a normal push (this generates the necessary binary files, and also makes sure the tests are still passing)
* Package the nupkg files
* Upload the nupkg files to NuGet using an API token. The API token has to be stored as a secret in the organisation.
* Upload the nupkg files to GitHub packages. This uses the default GitHub secret token.
* Create a GitHub release. We currently don't attach any custom assets to this release, since there isn't a …

👷‍♂️ Add GitHub actions work flow for building/testing and releasing

---

.github/workflows/dotnet-publish.yml

Fixes a bug with the publish GitHub action so that the create release step works.
See #198 
To make the automatic publish workflow work.
It sets the correct token in the environment variable that the create-release action expects.
This is the recommended way based on the example.
Should be trivial. Feel free the squash.

🐛 Add missing GitHub token to release creation step

---

.github/workflows/dotnet-publish.yml

Final attempt at fixing the GitHub package push in our new actions.
Ref #198 
This fixes the push to GitHub packages so we can use that as parallel publishing source.
It sets the authentication key to the GitHub authentication token.
Feel free to squash.

👷‍♂️ Use the GitHub token as key when authenticating

---

Bearded.Utilities/Core/AsyncAtomicUpdating.cs
Bearded.Utilities/Input/InputManager.cs

This PR restores the original implementation of the input manager with our own input state snapshots to ensure we only miss inputs if they happen within a frame.

🐛 Fix input handling by going back to our own snapshots

---

Bearded.Utilities/Geometry/Angle.cs
Bearded.Utilities/Geometry/Direction2.cs
Bearded.Utilities/Geometry/PolarPosition.cs
Bearded.Utilities/Geometry/Rectangle.cs
Bearded.Utilities/SpaceTime/2d/Acceleration2.cs
Bearded.Utilities/SpaceTime/2d/Difference2.cs
Bearded.Utilities/SpaceTime/2d/Position2.cs
Bearded.Utilities/SpaceTime/2d/Velocity2.cs
Bearded.Utilities/SpaceTime/3d/Acceleration3.cs
Bearded.Utilities/SpaceTime/3d/Difference3.cs
Bearded.Utilities/SpaceTime/3d/Position3.cs
Bearded.Utilities/SpaceTime/3d/Velocity3.cs
Bearded.Utilities/SpaceTime/Squared.cs
Bearded.Utilities/SpaceTime/angular/AngularAcceleration.cs
Bearded.Utilities/SpaceTime/angular/AngularVelocity.cs
Bearded.Utilities/SpaceTime/gravity/Mass.cs
Bearded.Utilities/SpaceTime/time/Frequency.cs
Bearded.Utilities/SpaceTime/time/Instant.cs
Bearded.Utilities/SpaceTime/time/TimeSpan.cs
Bearded.Utilities/SpaceTime/undirected/Acceleration.cs
Bearded.Utilities/SpaceTime/undirected/Speed.cs
Bearded.Utilities/SpaceTime/undirected/Unit.cs

This adds another overload for ToString methods, that takes nullable format as its only parameter. I've also normalized the implementations to follow similar formatting.
Closes #196

🔠 Add format-only ToString to SpaceTime types

---

Bearded.Utilities/Collections/StaticPriorityQueue.cs

What the title says. I made PriorityQueue implement IEnumerable.
N/A - I needed this to better debug TD's pathfinding.
Debugging is the main use case I can think of, but I'm sure there are other ways this might be useful? I do find myself enumerating regular queues from time to time...
The most straightforward way possible
None.
No reason to overcomplicate, unless...
If the priority queue is changed during enumeration, the behaviour is pretty much undefined (we could skip or duplicate entries, or maybe even return `default` or array overflow(?)). Solutions are to keep a 'version' int around and crash (before? after? the 'yield return' - or maybe we need a separate enumerator type) or to use a List instead of an array to store the entries and refer to List.GetEnumerator
The code is …

🥈 Allow enumeration of priority queues

---

Bearded.Utilities/Threading/BackgroundActionQueue.cs
Bearded.Utilities/Threading/IActionQueue.cs
Bearded.Utilities/Threading/ManualActionQueue.cs

Refactored the IActionQueue interface and implementors to be simpler and properly Async, making them easier to use in async cases (at the cost of a little bit of overhead of creating task completion sources).
Working with Tasks and async/await is nicer than doing stuff more manually.
See code. Quite simple.
The whole interface is different now.
This is the simplest I think.

🧵 Make IActionQueue async

---

Bearded.Utilities.Tests/Generators/DirectionGenerators.cs
Bearded.Utilities.Tests/Geometry/CircularArc2Tests.cs

This PR rewrites the circular arc tests to no longer be grouped by the member they test.
N/A
We want to focus on behaviours, rather than members in our tests.
The reason we are rewriting an existing test is to have a single canonical example that we can refer contributors to the bearded libraries to as part of our effort to improve test coverage.
This PR attempts to maintain the current test coverage, but rebrand its tests to talk more about the cause and effect, rather than the members it affects. This was largely possible without changing the tests, though some reordering took place to make things make more sense together.
There are sort of two naming schemes in use now:
1. `Cause_Effect`
2. `Fact`
The first is used mostly for the factory methods (e.g. …

✅ Rewrite circular arc tests to untie from members

---

.github/workflows/dotnet-build.yml
.github/workflows/dotnet-publish.yml
Bearded.Utilities.Benchmarks/Bearded.Utilities.Benchmarks.csproj
Bearded.Utilities.Testing.Tests/Bearded.Utilities.Testing.Tests.csproj
Bearded.Utilities.Testing/Bearded.Utilities.Testing.csproj
Bearded.Utilities.Tests/Bearded.Utilities.Tests.csproj
Bearded.Utilities.Tests/Collections/PriorityQueueTests.cs
Bearded.Utilities/Algorithms/CoffmanGraham.cs
Bearded.Utilities/Bearded.Utilities.csproj

.Net6 is out, let's support it!
- target .net6 on top of 5 and 3.1 with all projects (except benchmarks which we only run on the latest framework)
- a couple of using statement changes to unambiguafy references that overlap with things added in .net6
- set lang-version to 10 in all projects (this doesn't break anything)
None at all I believe. We still target 5 and 3.1 as before. They are officially supported until May/December next year, so we can keep them around for now as well.

🆙 Add support for .net6 and C#10

---

.git-blame-ignore-revs

Hides the almost 100% file rewrite from #251
Because blaming people is fun?

🙈 Hide namespace commit from git blame

---

.github/dependabot.yml

Supports dependabot config.
Automatically updates dependencies, keeping the library up-to-date. This is especially useful in light of other bearded libraries using this, to make sure they keep consistent versions of common dependencies like OpenTK.
This config is copied verbatim from beardgame/audio repository.
Feel free to squash and merge.

🆙 Add dependabot config

---

.github/workflows/dotnet-publish.yml

Changes the automatic discovery of packages into a list of commands per package.
Right now it will also automatically release the benchmarks project. In general, we probably want to be in control of what we push to NuGet.
beardgame/graphics#46 solved a similar issue for the graphics library. This follows that same approach.
This can't be tested until we next release a new version.

🐛 Explicitly provide packages to publish

---

Bearded.Utilities/Bearded.Utilities.csproj

This PR updates all the OpenTK dependencies in one go.
It also removes some unnecessary code that was there for .NET standard 2.1 only, which is no longer supported.
Replaces #256 and #262 
Dependabot only does single dependencies at a time. The OpenTK dependencies break if you use different versions for the different dependencies.
Manually updating the csproj, since even the NuGet UI doesn't like the one-by-one updating of packages.
Projects implicitly depending on the OpenTK version we provide will be broken.
We could switch to the full OpenTK package which also pulls in OpenAL and other libraries, so we only ever have a single dependency to deal with.
We had to also add an explicit dependency to `System.Runtime.CompilerServices.Unsafe`, because both `OpenTK` and …

⬆ Manually upgrade OpenTK in one batch

---

.github/release.yml
.github/workflows/dotnet-build.yml
.github/workflows/dotnet-publish.yml

This PR makes some improvements to the GitHub actions, doing some cleanup and maintenance on them, as well as migrating it to an actually maintained GitHub action creating a release, which will automatically include PR titles as release notes.
Closes #255 
* The existing GitHub action is deprecated; this moves us to an actually maintained GitHub action.
* Having release notes will include the release notes as snippet in dependabot PRs, as well as looking more official 🤓
Manual changes based on the documentation of the [new action](https://github.com/softprops/action-gh-release) as well as [GitHub documentation](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes) to create the …

🏆 Improve release pipeline and generate release notes

---

.github/dependabot.yml

This instructs dependabot to always combine upgrades within the xUnit and OpenTK groups (separately). 
We have multiple dependencies, but they tend to be released together. This avoids version conflicts.
Reused the config from TD and audio, both of which have proven to be successful in achieving the desired behaviour.
I've also modified "assignee" to "reviewer", since that's what I _actually_ end up doing for these PRs 😁

🫂 Group xUnit and OpenTK dependabot upgrades

---

.github/workflows/dotnet-build.yml
.github/workflows/dotnet-publish.yml

This PR replaces the copy of the workflow templates from beardgame/.github with a much simpler one that refers to the files in that same repository, so they automatically pick up any changes.
It saves on duplication.
Manually porting over the `jobs` section of the yaml files.

🧑‍🚒 Replace copied workflows with workflow references

---

Bearded.Utilities.Testing.Tests/Bearded.Utilities.Testing.Tests.csproj
Bearded.Utilities.Tests/Bearded.Utilities.Tests.csproj
Bearded.Utilities.Tests/Geometry/RectangleTest.cs
Bearded.Utilities/Geometry/Rectangle.cs

This PR fixes the `Rectangle.FromSides` method to create the correct rectangle. Right now it has the X and Y dimensions flipped.
To have correctly oriented rectangles.
First added a test case to reproduce the bug, then fixed it. Also added some other basic test cases for similar code paths for consistency. We could be testing `Rectangle` much more but that was not the intent of this PR.
If people considered this a feature... they really shouldn't
I disabled the .NET 5 tests since .NET 5 is no longer supported and it wouldn't run locally on my machine. We should probably stop supporting it altogether but I'll leave that to a separate PR.

🐛 Fix Rectangle.FromSides creation

---

Bearded.Utilities.Tests/Algorithms/CoffmanGrahamTests.cs
Bearded.Utilities/Algorithms/CoffmanGraham.cs
Bearded.Utilities/Bearded.Utilities.csproj
Bearded.Utilities/Graphs/AdjacencyListDirectedAcyclicGraph.cs
Bearded.Utilities/Graphs/AdjacencyListDirectedGraph.cs
Bearded.Utilities/Graphs/DirectedGraphBuilder.cs

This PR downgrades the `System.Collections.Immutable` reference to 6.0.0.
It also replaces some references to `ImmutableList` to `ImmutableArray` which is a more appropriate data structures in our use cases.
`System.Collections.Immutable` isn't a "true" NuGet package. Rather it is part of the .NET runtime. Therefore, as long as we support .NET 6, we should stick with the current version.
Now... why not drop .NET 6 support you might ask? Well, because the Roslyn Source Generators in Rider completely break down if you target a runtime newer than .NET 6. If we want to be able to keep using types from `Bearded.Utilities` in binaries referenced by source generators (for example, in TD we use `Id<T>`) we will want to stick with .NET 6 for now.
One change to consider is to split the complex …

⬇️ Downgrade System.Collections.Immutable
